[package]

name = "gtfs-map"
version = "0.0.1"
authors = ["George Schneeloch <bostonbusmap@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
hyper = "<0.10"
getopts = "*"
rusqlite = "*"
byteorder = "*"
xml-rs = "*"
serde = "*"
serde_derive = "*"
